### ISSUE TITLE
Improve Evocrash user guide documentation: describe Evocrash parameterization in config.properties

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/EvoCrash#16]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: Evocrash latest version
- **Execution Environment**: All
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Please, improve DSpot documentation describing the purpose and acceptable values (and range) for the parameters included in config.properties:

```
criterion=CRASH
sandbox=TRUE
test.random=0
functional.mocking.p=0.8
functional.mocking.percent=0.5
minimize=TRUE
headless.chicken.test=FALSE
population=80
search.budget=600
condition.stopping=
timeout.global=3600
frame.level=3
virtual.fs=TRUE
class.loader.separate=FALSE
calls.replace=FALSE
recursion.max=50
jar.tools.location=
fields.static.reset=FALSE
net.virtual=FALSE
exception.type=java.lang.ClassCastException
#the working directory is Demo/
path.test=src/GGA-tests/java/
path.log=src/resources/logs/XWIKI/XWIKI-13916/XWIKI-13916.log
path.libs=src/resources/targetedSoftware/XWIKI-bins/XWIKI-8.4/
```
See [DSpot](https://github.com/STAMP-project/dspot/blob/master/README.md) and [Descartes](https://github.com/STAMP-project/pitest-descartes/blob/master/README.md) readme.md for examples of describing parameters (for instance those accepted within the command line or in Maven descriptors).

#### Steps to reproduce
N/A

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by xdevroey** [comment]
See https://github.com/STAMP-project/botsing/issues/15
