### ISSUE TITLE
Improve Evocrash documentation: explain how to execute Evocrash with different clients: CLI, Gradle

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/EvoCrash#17]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: N/A
- **Severity**: feature
- **Tool/Service/Component**: Evocrash, latest version
- **Execution Environment**: All
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
This request for documentation enhancement it motivated by two reasons:
1- As Evocrash adopter (user, use case provider) we need to understand how to invoke Evocrash from latest source code or downloaded binaries. This goes beyond the [demo](https://github.com/STAMP-project/EvoCrash-demo/blob/master/README.md) description.
2- As developers of Eclipse plugins, we need to understand the different options to configure and launch Evocrash from Eclipse IDE.

Inspecting Evocrash [demo](https://github.com/STAMP-project/EvoCrash-demo/blob/master/README.md), and concretely the [build.gradle](https://github.com/STAMP-project/EvoCrash-demo/blob/master/Demo/build.gradle) descriptor, it seems that executing Evocrash requires:
1- Include Evocrash library (evocrash-lib/evocrash-1.0.0.jar) in classpath
2- Include target libraries (e.g. XWiki, ActiveEon, etc) in classpath
3- Include Evocrash launcher source code (src/main/java) and resources (src/resources) in classpath
4- Invoke Evocrash launcher with Java: eu.stamp_project.evocrash.demo.Application

I am omitting the configuration for running generated tests. 

Could you please describe in detail in documentation how to run Evocrash in CLI and Gradle from the built Evocrash library, built using Maven as explain in [Evocrash documentation](https://github.com/STAMP-project/EvoCrash/blob/master/README.md)?

#### Steps to reproduce
N/A
#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by xdevroey** [comment]
See https://github.com/STAMP-project/botsing/issues/15
